const String whisperSystemPrompt = 'Contexte : dictée d\'une ordonnance '
    'médicale en français.\n'
    'Transcription fidèle. Ne pas inventer. Si un mot est incertain, le '
    'laisser proche du son.\n'
    'Extraire aussi le patient s\'il est mentionné.\n'
    'Termes fréquents : mg, g, UI, ml, comprimé, gélule, perfusion, bolus.\n'
    'Voies : IV, IM, SC, PO.\n'
    'Dispositifs : VVP, PICC, PAC.\n'
    'Médicaments : Ceftriaxone, Ceftazidime, Piperacilline + Tazobactam, '
    'Ganciclovir, Amphotericine B, Amikacine, '
    'Amoxicilline + Acide Clavulanique, Aztreonam, Cefepime, '
    'Sulfamethoxazole + Trimethoprime, Oxacilline, Caspofungine, '
    'Cefazoline, Cefotaxime, Ciprofloxacine, Daptomycine, Clindamycine, '
    'Erythromycine, Metronidazole, Gentamicine, Ertapenem, Cefoxitine, '
    'Meropenem, Micafungine, Tobramycine, Temocilline, Ofloxacine, '
    'Cloxacilline, Penicilline G, Piperacilline, Rifampicine, Teicoplanine, '
    'Levofloxacine, Imipeneme + Cilastatine, Fluconazole, Vancomycine, '
    'Dalbavancine, Amoxicilline, Clarithromycine, Aciclovir, Linezolide.\n'
    'Expressions : sur VVP, sur PAC, perfusion, IV.\n'
    'Fréquence : 1 fois par jour, 2 fois par jour, 3 fois par jour, x1/j, '
    'x2/j, x3/j, toutes les 8 heures.\n'
    'Format attendu (répéter par médicament) :\n'
    '- Patient : Nom Prénom (si disponible)\n'
    '- Médicament : ...\n'
    '- Dose : ...\n'
    '- Posologie : ...\n'
    '- Voie : ...\n'
    '- Fréquence : ...\n'
    '- Durée : ...';
